name: Strava Auto Kudos Playwright
on:
  schedule:
    - cron: '0,20,40 * * * *'
  workflow_dispatch:

jobs:
  run-kudos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium
      - name: Run script
        env:
          STRAVA_COOKIE: ${{ secrets.STRAVA_COOKIE }}
        run: python -u give_kudos.py
